// Tracks link clicking
user_pref("beacon.enabled", false);
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.fullscreen.animate", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.pocket.enabled", false);
user_pref("browser.showQuitWarning", true);
user_pref("browser.urlbar.autoFill", false);
user_pref("browser.urlbar.doubleClickSelectsAll", false);
user_pref("browser.urlbar.formatting.enabled", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("general.autoScroll", true);
user_pref("layers.acceleration.force-enabled", true);
user_pref("layout.word_select.eat_space_to_next_word", false);
user_pref("media.fragmented-mp4.exposed", true);
user_pref("media.fragmented-mp4.ffmpeg.enabled", true);
user_pref("media.mediasource.format-reader.webm", true);
user_pref("media.block-autoplay-until-in-foreground", false);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.interposition.enabled", false);
user_pref("dom.ipc.processCount", 2);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("media.gpu-process-decoder", true);
user_pref("layers.gpu-process.enabled", true);
// Because fuck you, Webkit
user_pref("layout.css.prefixes.webkit", false);
user_pref("network.IDN_show_punycode", true);
